### ISSUE TITLE
vts --add  error

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/vts-backend#15]
Hello, 

I generated the following surfac,e:

https://vtsbackend.canterbury.ac.nz/mapproxy/melown2015/surface/linz/NZ8mDEMLod21/?pos=obj,174.593786,-41.524829,fix,218.19,0.00,-90.00,0.00,999917.25,45.00

 all seems fine but as I try to add it store using the command below, I get a "no navtile" error. It appears to be related to a small island of the north cape of new zealand. Any ideas what's happening?

vts@seesvts01p:~/store/stage.melown2015$ vts /var/vts/store/stage.melown2015 --add --tileset https://vtsbackend.canterbury.ac.nz/mapproxy/melown2015/surface/linz/NZ8mDEMLod21 --top
2020-10-02 00:57:26 I3 [18956(main)]: Requested to add remote tileset pointing to "https://vtsbackend.canterbury.ac.nz/mapproxy/melown2015/surface/linz/NZ8mDEMLod21". Generating temporary remote tileset. {vts.cpp:add():2077}
2020-10-02 00:57:28 I3 [18956(add(linz-NZ8mDEMLod21))]: Adding tileset <linz-NZ8mDEMLod21> (from "/var/vts/store/stage.melown2015/tmp/tileset-to-add"). {change.cpp:add():1173}
2020-10-02 00:57:30 I3 [18956(add(linz-NZ8mDEMLod21))]: Generating 1 glue(s): {change.cpp:generateGluesImpl():1056}
2020-10-02 00:57:30 I3 [18956(add(linz-NZ8mDEMLod21))]:     #1/1 <JdFDEM-worldLod23_linz-NZ8mDEMLod21>. {change.cpp:generateGluesImpl():1058}
2020-10-02 00:57:30 I3 [18956(add(linz-NZ8mDEMLod21))]: Trying to generate glue #1/1 <JdFDEM-worldLod23_linz-NZ8mDEMLod21>. {change.cpp:createGlue():807}
2020-10-02 00:57:30 I3 [18956(add(linz-NZ8mDEMLod21)/1:JdFDEM-worldLod23_linz-NZ8mDEMLod21)]: Memory occupied before glue creation: 0.710625 GiB (of which 0.000000 GiB is swapped). {change.cpp:reportMemoryUsage():85}
2020-10-02 00:57:30 I3 [18956(add(linz-NZ8mDEMLod21)/1:JdFDEM-worldLod23_linz-NZ8mDEMLod21)]: (glue) Calculating generate set. {glue.cpp:createGlue():504}
2020-10-02 00:57:30 I3 [18956(add(linz-NZ8mDEMLod21)/1:JdFDEM-worldLod23_linz-NZ8mDEMLod21)]: (glue) Calculating generate set. {glue.cpp:buildGenerateSet():445}
2020-10-02 00:57:37 I3 [18956(add(linz-NZ8mDEMLod21)/1:JdFDEM-worldLod23_linz-NZ8mDEMLod21)]: (glue) Generate set calculated. {glue.cpp:createGlue():524}
2020-10-02 00:57:42 E2 [18956(add(linz-NZ8mDEMLod21)/1:JdFDEM-worldLod23_linz-NZ8mDEMLod21/9-250-153)]: Tile 9-250-153 has no navtile. {tileset.cpp:getNavTile():1451}
vts: Tile 9-250-153 has no navtile. @{tileset.cpp:getNavTile():1451}

**Comment by vaclavblazek** [comment]
I'm able to replicate your problem, will have a look. Please, do not remove datasets.

**Comment by jrjdavidson** [comment]
Just fyi this is the orginal dataset:
https://koordinates.com/from/data.linz.govt.nz/layer/51768/
From that - I created a vrt and processed the data manually (i.e. not using mapproxy-setup-resource). The same process as in the cadastre tutorial.

**Comment by jrjdavidson** [comment]
Hi Vaclav,
Just checking if you had a chance to look at this. 
I suspect that the fact the DEM is broken into seperate islands might be the cause of the issue, so I might just break the dataset into smaller chunks and see if that works?
I'll need to have something ready to go for testing purposes in the next week or so.

**Comment by vaclavblazek** [comment]
Hi Jonathan,

I've finally got time to investigate your problem.

I have pretty good idea what's happening. Yes, it's connected to fragmented dataset: Manawatāwhi islands at LOD 9 are tiny dot in otherwise empty tile. When generating metatile, this dot is probably warped either as nothing or too few pixels to calculate needed data and tile is reported as lacking mesh and navtile which is in discrepancy with tileindex used for dataset merging.

One simple workaround would be to add sea as a "background" in your dataset.

However, I'd like to fix this problem. Would it be possible to provide me with your source DEM dataset to play with?
Also, what linux distro do you use? There could be (and are) differences in GDAL versions.

V.

**Comment by jrjdavidson** [comment]
Thanks, 
we use  Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-118-generic x86_64)
the source DEM is here : https://koordinates.com/from/data.linz.govt.nz/layer/51768/
koordinates is free to sign up and download data, which is probably the easiest for you to get as the dataset is 17Gb. Unless you would like me to provide the exact dataset (including vrt file)?

**Comment by vaclavblazek** [comment]
I've tried to download the dataset but the page says "This download is over the size limit of 15.0 GB."
Well, if you would be so kind to publish your exact dataset somewhere it'd be great.

**Comment by jrjdavidson** [comment]
Apologies about that, not sure how I got the dataset in that case? 
I sent you a message at your @melowntech.com address with a link

**Comment by vaclavblazek** [comment]
Hi, thanks, already downloading.

**Comment by vaclavblazek** [comment]
One more thing, how did you set up mapproxy resource for this dataset? Via `mapproxy-setup-resource` or manually?

**Comment by jrjdavidson** [comment]
Manually, using the method on the tutorial.

**Comment by jrjdavidson** [comment]
Vaclav, any tips on quickly adding sea-level to the vrt dataset

**Comment by vaclavblazek** [comment]
OK, so I found the cause(s), did some fixes and also some updates.

Anyway, there's a brand new `vts-mapproxy` package version 1.69 for Ubuntu 18.04 available in our package repo.
NB: Do not forget to restart mapproxy after package upgrade (i.e. `systemctl restart vts-backend-mapproxy.service`).

Unfortunately, you need to regenerate `dem` dataset overview; if you did it manually and you want to update it manually, please use `cubicspline` filter. In this case, it would be better to update resource revision to flush any possible caching on the way.

Or, you can use the `mapproxy-setup-resource` tool which I finally provided with `--linkDataset` command line options to link the dataset instead of copying it (copy doesn't really work well some dataset types, like VRT). In this case, you'd get new dataset with everything needed.

You have to make sure that you use proper program: `/usr/bin/mapproxy-setup-resource` wrapper script, not the binary itself -- it inject proper `mapproxy` configuration to communicate with running mapproxy. You can check it with `which mapproxy-setup-resource`. Or just use full path.

Please, let me know how it works.

**Comment by jrjdavidson** [comment]
Thanks Vaclav for both the update and the --linkDataset option! Will update when tested.

**Comment by jrjdavidson** [comment]
maybe a bug with the new --linkDataset?

vts@seesvts01p:~/mapproxy/datasets/NZ8mDEM$ mapproxy-setup-resource --referenceFrame melown2015 --id NZ8mDEM --group linz --dataset NZ8mDEM.vrt --attribution "<a href=http://data.linz.govt.nz>Sourced from LINZ. CC BY 4.0</a>" --bottomLod 21 --linkDataset 1
2020-10-23 01:12:26 I3 [96382(main)]: Loaded configuration from "/etc/vts/mapproxy/mapproxy-setup-resource.conf". {program.cpp:configureImpl():540}
2020-10-23 01:12:26 I3 [96382(main)]: [mapproxy-setup-resource] Config:
mapproxy.dataRoot = "/var/vts/mapproxy/datasets"
mapproxy.definitionDir = "/etc/vts/mapproxy/auto.d"
mapproxy.ctrl = "/var/run/vts-backend-mapproxy.ctrl"
referenceFrame = melown2015
credits.firstNumericId = 32768
bottomLod = 21
 {main.cpp:configure():222}
2020-10-23 01:12:26 I4 [96382(main)]: Using resource ID <melown2015/linz/NZ8mDEM>. {main.cpp:run():730}
2020-10-23 01:12:26 I4 [96382(main)]: Checking for resource existence. {main.cpp:run():734}
2020-10-23 01:12:26 I4 [96382(main)]: Measuring dataset. {main.cpp:run():754}
2020-10-23 01:12:26 I3 [96382(main)]: Using credit ID <auto-a-href-http-data-linz-govt-nz-sourced-from-linz-cc-by-4-0-a> for attribution "<a href=http://data.linz.govt.nz>Sourced from LINZ. CC BY 4.0</a>". {main.cpp:attribution2credit():452}
2020-10-23 01:12:26 I4 [96382(main)]: Copying/symlinking dataset to destination. {main.cpp:operator()():798}
2020-10-23 01:12:26 I4 [96382(main)]: Generating dataset overviews. {main.cpp:createVrtWO():581}
2020-10-23 01:12:26 I4 (ovr) [96382(main)]: Generating height overviews. {main.cpp:createVrtWO():586}
2020-10-23 01:12:26 I3 (dem) [96382(main)]: Creating dataset base in "/var/vts/mapproxy/datasets/NZ8mDEM.vrt.faaf24bf3b337161aa8a1f43a94cb216.tmp/vttwo/dem/dataset" from "/var/vts/mapproxy/datasets/NZ8mDEM.vrt.faaf24bf3b337161aa8a1f43a94cb216.tmp/vttwo/dem/./original". {generatevrtwo.cpp:buildDatasetBase():527}
2020-10-23 01:12:26 E2 (dem) [96382(main)]: gdal error 4: ../../original-dataset/NZ8mDEM.vrt: No such file or directory {geodataset.cpp:GDALErrorHandler():77}
2020-10-23 01:12:26 E2 (dem) [96382(main)]: Failed to open dataset "/var/vts/mapproxy/datasets/NZ8mDEM.vrt.faaf24bf3b337161aa8a1f43a94cb216.tmp/vttwo/dem/./original". {geodataset.cpp:open():297}
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open dataset "/var/vts/mapproxy/datasets/NZ8mDEM.vrt.faaf24bf3b337161aa8a1f43a94cb216.tmp/vttwo/dem/./original". @{geodataset.cpp:open():297}
/usr/bin/mapproxy-setup-resource: line 8: 96382 Aborted                 (core dumped) /opt/vts/bin/mapproxy-setup-resource "$@" -f "${CONFIG}"

**Comment by vaclavblazek** [comment]
Oh, I tested it only with absolute paths, my bad.
So, I updated it,  please install package `1.70`

Now, `--linkDataset` is not a simple boolean (although it acts as one, you can use `0`/`1` or `false`/`true`), you use use:

-  `nolink` (eq. to false/0) to copy source dataset (default value if option is not used)
-  `absolute` (eq. to true/1) to make a symlink to absolute source dataset path (implicit value if only `--linkDataset` is used without value)
-  `relative` to make a symlink relative from dst dataset

**Comment by jrjdavidson** [comment]
Thanks for that Vaclav. I created the dataset manually overnight (https://vtsbackend.canterbury.ac.nz/mapproxy/melown2015/surface/linz/NZ8mDEM/) and it seems to freeze when using vts --add. See below. I will try again using mapproxy-setup-resource  and --linkDataset later

vts@seesvts01p:~$ vts /var/vts/store/stage.melown2015/ --add --tileset https://v                                                                      tsbackend.canterbury.ac.nz/mapproxy/melown2015/surface/linz/NZ8mDEM --top
2020-10-23 22:39:38 I3 [99173(main)]: Requested to add remote tileset pointing t                                                                      o "https://vtsbackend.canterbury.ac.nz/mapproxy/melown2015/surface/linz/NZ8mDEM"                                                                      . Generating temporary remote tileset. {vts.cpp:add():2077}
2020-10-23 22:39:38 I3 [99173(add(linz-NZ8mDEM))]: Adding tileset <linz-NZ8mDEM>                                                                       (from "/var/vts/store/stage.melown2015/tmp/tileset-to-add"). {change.cpp:add():                                                                      1173}
2020-10-23 22:39:39 I3 [99173(add(linz-NZ8mDEM))]: Generating 1 glue(s): {change                                                                      .cpp:generateGluesImpl():1056}
2020-10-23 22:39:39 I3 [99173(add(linz-NZ8mDEM))]:     #1/1 <JdFDEM-worldLod23_l                                                                      inz-NZ8mDEM>. {change.cpp:generateGluesImpl():1058}
2020-10-23 22:39:39 I3 [99173(add(linz-NZ8mDEM))]: Trying to generate glue #1/1                                                                       <JdFDEM-worldLod23_linz-NZ8mDEM>. {change.cpp:createGlue():807}
2020-10-23 22:39:39 I3 [99173(add(linz-NZ8mDEM)/1:JdFDEM-worldLod23_linz-NZ8mDEM                                                                      )]: Memory occupied before glue creation: 0.326176 GiB (of which 0.000000 GiB is                                                                       swapped). {change.cpp:reportMemoryUsage():85}
2020-10-23 22:39:39 I3 [99173(add(linz-NZ8mDEM)/1:JdFDEM-worldLod23_linz-NZ8mDEM                                                                      )]: (glue) Calculating generate set. {glue.cpp:createGlue():504}
2020-10-23 22:39:39 I3 [99173(add(linz-NZ8mDEM)/1:JdFDEM-worldLod23_linz-NZ8mDEM                                                                      )]: (glue) Calculating generate set. {glue.cpp:buildGenerateSet():445}
2020-10-23 22:39:39 I3 [99173(add(linz-NZ8mDEM)/1:JdFDEM-worldLod23_linz-NZ8mDEM                                                                      )]: (glue) Generate set calculated. {glue.cpp:createGlue():524}

**Comment by jrjdavidson** [comment]
Can confirm that creating the same dataset with mapproxy-setup-resource, it appears to hang at the same spot. I let it run for a few hours then gave up

**Comment by jrjdavidson** [comment]
also- i think you might have mixed up the relative and absolute in--linkDataset, mapproxy-setup-resource failed with the realtive but succeded with relative?

**Comment by vaclavblazek** [comment]
### Caveats

Be aware that mapproxy-setup-resource converts source dataset to mapproxy dataset only once (it is stored in directory named filename + md5(filename)) and is reused in reruns with different settings. To force overview generation you have to either remove the generated dataset, rename source or change source contents.

### Merging

I'm affraid that's not freeze -- that's a consequence of your dataset to be too fragmented and thus having too large number of border tiles. It takes ages to generate all of these tiles when merging.

You can add sea (h=0) in your dataset (`NZ8mDEM.vrt`), the change is rather simple:
```
-    <NoDataValue>-32767</NoDataValue>
+    <NoDataValue>0</NoDataValue>
+    <HideNoDataValue>1</HideNoDataValue>
```

NoData + hiding means that nodata value is changed to 0, i.e. any hole in the dataset is replaced with 0 and the dataset and since the nodata information is hidden it s treated as any other valid value.

Also, add `--background 0` to `mapproxy-setup-resource`: as overviews are broken into _tiles_ any tile full of zeroes will not be physically written to disk, limiting number of generated files.

### Relative/absolute links

at my setup it leads to given results
- absolute:
    ```
    lrwxrwxrwx 1 vasek vasek   62 Oct 24 08:06 NZ8mDEM.vrt -> /home/vasek/git/vts/mapproxy/mapproxy/output/8mDEM/NZ8mDEM.vrt
    ```
- relative:
    ```
    lrwxrwxrwx 1 vasek vasek   36 Oct 24 08:08 NZ8mDEM.vrt -> ../../../../output/8mDEM/NZ8mDEM.vrt
    ```

In both cases, mapproxy runs as expected.

**Comment by jrjdavidson** [comment]
thanks Vaclav for the time you're putting into this! 

just tried re-running `mapproxy-setup-resource` using the `--background 0` option and I get `mapproxy-setup-resource: unrecognised option '--background'
`

And yes, I think you're right about the --linkDataset option

I'll also let the other dataset run and see if it eventually merges the tilesets

**Comment by vaclavblazek** [comment]
Sorry, you were faster than me. I added the `--background` option to mapproxy-setup-resource and forgot to make a new package. If you want to use `--background`, please install v 1.71 of mapproxy.

**Comment by jrjdavidson** [comment]
Thanks, it's running fine now.

**Comment by jrjdavidson** [comment]
Hi Vaclav

I generated the  dataset using `mapproxy-setup-resource` and the `--background` option, the result is here and looks good 
https://vtsbackend.canterbury.ac.nz/mapproxy/melown2015/surface/linz/NZ8mDEMv3/

Again, when trying to add the dataset using vts --add, it 'hangs' at `Generate set calculated.`, been there for 12 hours now. I'll just leave it running for now and see if it resolves produces a result

**Comment by vaclavblazek** [comment]
There are few problems, some solvable, some not.
First of all: NZ dataset is really huge.

Your world is generated to LOD 21 and NZ is generated only to LOD 17. Due to internal workings of VTS the extra NZ tiles that hide world tiles. So, the glue generate set is realy gigantic (logged as `generate: 2622323753`, i.e. 2.6 billion tiles).

I generated NZ dataset to LOD 21 (via `--bottomLod 21`), it took longer time to produce more detailed tiling.
Now, the generate set is `generate: 718921` which is way smaller. It cannot get smaller for you setup.
I've got first 0.5% logged after 13m23s, extrapolating it should take something like two days when combining my local NZ and your remote world. It would be probably faster when done locally, not downloading data halfway around the world.

My test merge log:
```2020-10-28 13:33:18 I3 [78735(main/1:DEM-worldJdF_8mDEM-nzdem.9)]: (glue) Generate set calculated. {glue.cpp:createGlue():524}
2020-10-28 13:46:41 I3 [78735(main/1:DEM-worldJdF_8mDEM-nzdem.9/21-1007335-630674)]: (glue) progress:   0.50 %. {progress.cpp:report():48}
2020-10-28 14:04:13 I3 [78735(main/1:DEM-worldJdF_8mDEM-nzdem.9/20-504203-315032)]: (glue) progress:   1.00 %. {progress.cpp:report():48}
```
 
Anothing thing that may make it faster is not using HTTPS, at least for merging. If you enable plain HTTP on your server then you can use schema-less URL when adding dataset, i.e. `//vtsbackend.cantenburry.ac.cz/...` VTS backend tools treat schema-less URL as HTTP URL and browser correctly uses the same schema as referrencing resource (HTML page od mapConfig or other JSON).

I hope this helps.

**Comment by jrjdavidson** [comment]
Vaclav- I'm really confused as I used the --bottomLod 21 flag. I checked the file and it looks to me that it is to 21. How can you tell that is is to level 17?

Also- where to see the `generate: 2622323753` log? 2 billion tiles is obviously enormous and the machine isn't set up for that kind of work.

And yes, the dataset is huge but if this is solvable, I hope that the map gets used extensively!

**Comment by vaclavblazek** [comment]
Sorry, my bad, I missed you have it already at LOD 21. It's logged with level I1 (info1), so it's not seen by default.

**Comment by jrjdavidson** [comment]
Ok, any idea why the generate set is so different between the two?
Not sure what you mean by level l1.

**Comment by vaclavblazek** [comment]
Log level info1, logged just after date and time:
```
2020-10-29 08:57:46 I1 [90600(main/1:DEM-worldJdF_8mDEM-nzdem.9)]: generate: 718921 {glue.cpp:createGlue():517}
                    ^^
```

The difference is caused by current VTS machinery: at given place, render tile from source with highest priority. For example, two datasets, let's call them `top` and `bottom` have this priority list:
- `top`
- glue(`top`, `bottom`)
- `bottom`
If there is no tile `x-y-z` in `top` then try glue(`top`, `bottom`). If even there is no tile, use tile from `bottom`. If even there is no tile, go down the tree and do the same for its children.
This leads to a problem when `top` is is not s deep as `bottom`: once you zoom past `top` dataset deepest LOD it disappears and `bottom` suddently appears.
Therefore you have to generate extra tiles in the glue to cover offending tiles from lower levels.

Yes, its inefficient, there are some ideas how to solve it currently there's no time for it.

And yes, there are billions of tiles in LODs 18-21 in your NZ dataset. Whole world (ignoring polar caps) in LODs 1-21 has ca. 1.4 trillion tiles.

**Comment by jrjdavidson** [comment]
How do I enable log level 1?

I think I understand your explanation, but it's still not clear to me how we have such a different generate sets (your 700k to my 2G) when merging two identical datasets?

**Comment by vaclavblazek** [comment]
Re logging:

For more detailed logging use command line option `--log.mask` which all our programs support. There's also `--log.file` option to log to given file and `--log.console` to enable or disable logging to `stderr` (on by default). For more detailed info you can run any our program (vts*, mapproxy*, etc). with `--help-all`.

Formal mask grammar is described in [dbglog readme](https://github.com/melowntech/libdbglog/tree/master/dbglog), but may seem too cryptic.

In simple language, mask is combination of log severities followed by log levels. There are 5 severities: info (`I`), warning (`W`), error (`E`) (and fatal and debug which are special) and 4 levels (1-4). So mask can be something like `I1W2E3` meaning log info messages with levels 1-4, warnings with levels 2-4 and errors wich levels 3-4. There are special masks `NONE` (nothing logged, not even fatal messages), `ALL` (everything logged + debug), `DEFAULT` (`I3E2W2`), `VERBOSE` (`I2E2W2`) and ND (no debug), i.e. all without debug.

Default for our progams is `DEFAULT`, i.e. `I3E2W2`. Please, be aware that enabling too verbose logging will generate huge amount of log information. Like a lot of text.

Re number of tiles:
In your case (both datasets up to LOD 21) need to generate only 700k border tiles between them. It's OK.

Only in my case, when I didn't force setup resource to generate dataset down to LOD 21 and it deducted LOD 17 from input dataset resolution I got 2.6b tiles when merging -- merge had to generate all these covering tiles.

**Comment by jrjdavidson** [comment]
ok, thanks for that.  I'll try the log.mask flag to see if I get the same generate sets and will investigate the other options to speed up processing. In any case, you solved the original problem so I'll close this issue!

**Comment by jrjdavidson** [comment]
Hi Vaclav, 
just a final update on all this.

You were correct about the level of detail difference between the two surfaces, except the world DEM was at LOD23 and the NZ DEM was at 21. The generate set it calculated was 33G tiles. 

I decided to re-process the world DEM to LOD17, and swap it out with the previous world surface. Then i added the fragmented version of NZ DEM (without sea level). 7M Tiles, 70 hours :
```
2020-11-03 03:50:41 I3 [125997(add(linz-NZ8mDEMv2)/1:JdFDEM-worldLod17_linz-NZ8mDEMv2)]: Glue <JdFDEM-worldLod17_linz-NZ8mDEMv2> created, duration: 70:12:58.645239. {change.cpp:createGlue():852}
2020-11-03 03:54:11 I3 [125997(add(linz-NZ8mDEMv2)/1:JdFDEM-worldLod17_linz-NZ8mDEMv2)]: Memory occupied after glue flush: 5.261143 GiB (of which 0.517849 GiB is swapped). {change.cpp:reportMemoryUsage():85}
2020-11-03 03:54:11 I3 [125997(add(linz-NZ8mDEMv2)/1:JdFDEM-worldLod17_linz-NZ8mDEMv2)]: Memory occupied after glue creation: 5.262203 GiB (of which 0.517796 GiB is swapped). {change.cpp:reportMemoryUsage():85}
2020-11-03 03:54:47 I4 [125997(main)]: All done. {vts.cpp:add():2093}
```
but at least it works!

A couple of lessons it took away from this is:

- The bottom surface should have a lower LOD level, or else you'll get huge generate sets when merging large datasets. It would be useful if the calculated generate set is logged as L3 -it's a bit of pain to troubleshoot at L1..

- It would be nice if boundLayers of higher LOD could be overlayed on a given surface, might save a bit of work, but not too much of big deal once you wrap your head around all the details.

**Comment by VrushalNCT** [comment]
Hi @vaclavblazek ,

I'm facing the same issue while generating the glue it has stuck for around more than 36 hours now.

I'm using [http://www.viewfinderpanoramas.org/](http://www.viewfinderpanoramas.org/) DEM data set and have processed it with the following options  
```--bottomLOD 21 --linkDatasets 1 --background 0 ``` using ```mapproxy-setup-resource``` tool.

But using this data set alone I'm not getting tiles at sea area it's transparent/black in the vts browser.

I think I need to add the spheroid surface data to storage at the bottom and the above data set on top of it in the storage. So that the black tiles or the tiles not available from top data sets will be served from the bottom data set. Please do correct me If I'm wrong. 

I added the above dataset(LOD 21) using ```--top``` option first, and then added the default speroid dataset using ```--bottom``` option 
```http://<Ip adress>/mapproxy/melown15/surface/.system/surface-speroid``` (LOD 22)

And it is stuck with the following log

```
2020-12-12 14:05:07 I3 [5165(main)]: Requested to add remote tileset pointing to "http://<Ip_adress>/mapproxy/melown2015/surface/.system/surface-spheroid/". Generating temporary remote tileset. {vts.cpp:add():2077}
2020-12-12 14:05:07 I3 [5165(add(spheroid_dem))]: Adding tileset <spheroid_dem> (from "/var/vts/store/stage.melown2015/tmp/tileset-to-add"). {change.cpp:add():1173}
2020-12-12 14:05:32 I3 [5165(add(spheroid_dem))]: Generating 1 glue(s): {change.cpp:generateGluesImpl():1056}
2020-12-12 14:05:32 I3 [5165(add(spheroid_dem))]:     #1/1 <spheroid_dem_melown-world_dem>. {change.cpp:generateGluesImpl():1058}
2020-12-12 14:05:32 I3 [5165(add(spheroid_dem))]: Trying to generate glue #1/1 <spheroid_dem_melown-world_dem>. {change.cpp:createGlue():807}
2020-12-12 14:05:32 I3 [5165(add(spheroid_dem)/1:spheroid_dem_melown-world_dem)]: Memory occupied before glue creation: 9.773075 GiB (of which 0.000000 GiB is swapped). {change.cpp:reportMemoryUsage():85}
2020-12-12 14:05:32 I3 [5165(add(spheroid_dem)/1:spheroid_dem_melown-world_dem)]: (glue) Calculating generate set. {glue.cpp:createGlue():504}
2020-12-12 14:05:32 I3 [5165(add(spheroid_dem)/1:spheroid_dem_melown-world_dem)]: (glue) Calculating generate set. {glue.cpp:buildGenerateSet():445}
2020-12-12 14:07:22 I3 [5165(add(spheroid_dem)/1:spheroid_dem_melown-world_dem)]: (glue) Generate set calculated. {glue.cpp:createGlue():524}
```
Based on the above conversation, I think the bottom dataset should have a lower LOD but in my case, it is higher (22).
But, I'm not sure about how to get a plain spheroid dataset with LOD 21 or lesser for the Earth.
Could you please guide me if I'm doing anything wrong?

**Comment by jrjdavidson** [comment]
Hi Vrushal,

there is a tutorial on how to set up a spheriod on the bng-maps section:
https://vts-geospatial.org/tutorials/bing-maps.html

go the section **Displaying the data**
_We need to define at least one “empty” spheroid-dem type of surface layer, with our bing layer in it’s definition._

set the lod range to the one you would like! Hopefully that solves your problem,

JD

**Comment by VrushalNCT** [comment]
Hello @jrjdavidson ,

Thank you very much. I think I managed to set up a spheroid-dem with LOD 18.
Now my storage looks like following,

Spheroid-dem (LOD 18)  --bottom
World-dem (LOD 21)   --top

I was expecting some improvement in processing time after lowering  Spheroid-dem LOD from 21 to 18. But still, I got the first 0.5% progress log after 3 hours. It was around the same for LOD 21 as well. (right now my server configuration is 400 GBs storage and 8 cores if that matters)

If we forecast based on the above data. It'll probably take the next 25 days for gluing to complete. (I'm assuming that it will take around 3 hours for every 0.5% progress). Is this much gluing time expected?

Could you please suggest some way to reduce this gluing time?

**Comment by jrjdavidson** [comment]
sorry,  I think you might just have a huge glue dataset and have to wait it out.

It might be worth thinking about how to set up the original dataset so that `mapproxy-setup-resource` generates sea tiles everywhere. that would probably be the easiest solution.

**Comment by ladislavhorky** [comment]
Hello all,

there is a (considerably not very clean) trick for this. Namely for the situation when you have a certain dataset and you wish to extend it over the globe or a part. There are a few catches though:
* If DEM tiles contain sea, for this to work they must have 0 value in ares with se, not NODATA
* NODATA inside dataset will not be filled (may be desired)
* It possibly relies on implementation detail in VRT, rather than on guaranteed feature.
* Pros are that you no longer need glue, possibly getting you from "impossible to do" territory.
* Cons is that `mapproxy-tiling` will now be quite long, unless we finally manage to optimize it somehow. You also lose some of the overall cleanness - you'll modify things that may surprise you later.

**Approach:**
place a solid sea dataset as a first entry in VRT, pixel-aligned with the rest of the data. This way the driver will return 0 for pixel if it does not encounter any other data _tile_ (will return NODATA if it encounters a tile and it has NODATA at that place).

Then continue as normal, using `--background 0` option for `mapproxy-setup-resource` is highly recommended.

The big "sea" dataset may be tedious... but VTS internally adds *solid* GDAL driver, so you can define it as a text file - sample file contents for Viewfinder:
```
$ cat viewfinder-panoramas.bg
[solid]
srs = GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
size = 432001x216001
tileSize = 256x256
geoTransform = -1.8000041666666667e+02,8.3333333333333339e-04,0.0000000000000000e+00,9.0000416666571539e+01,0.0000000000000000e+00,-8.3333333333333339e-04

[band]
value = 0
dataType = Int16
colorInterpretation = Undefined
```
The trickiest part is of course to set the correct geotransform as this defines resolution and extents of the dataset. Sometimes, the original VRT will help.

Corresponding start of VRT:
```
<VRTDataset rasterXSize="432001" rasterYSize="216001">
  <SRS>GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]</SRS>
  <GeoTransform> -1.8000041666666667e+02,  8.3333333333287781e-04,  0.0000000000000000e+00,  9.0000416666571539e+01,  0.0000000000000000e+00, -8.3333333333287781e-04</GeoTransform>
  <VRTRasterBand dataType="Int16" band="1">
    <NoDataValue>-32768</NoDataValue>
    <SimpleSource>                                                                        \
      <SourceFilename relativeToVRT="1">./viewfinder-panoramas.bg</SourceFilename>         > This has to be added manually
      <SourceBand>1</SourceBand>                                                          /
      <SourceProperties RasterXSize="432001" RasterYSize="216001" DataType="Int16" BlockXSize="256" BlockYSize="256" />
      <SrcRect xOff="0" yOff="0" xSize="432001" ySize="216001" />                       /
      <DstRect xOff="0" yOff="0" xSize="432001.000000236" ySize="216001.000000118" />  /
    </SimpleSource>                                                                   /
    <SimpleSource>
    ... automatic content
    ...
```

Otherwise I agree with Jonathan - VTS tries to be quite clean an generic and in this situation you are really asking for a lot of work. The glue may turn out to be 10s of GBs in this case (possibly bigger than original DEM, the glue being mesh at much higher resolution). So you can now accept that or look for workarounds to ease it for VTS like above. 

In the future, we should be able to use detailed textures for coarse geometries, which will completely solve this, but this requires WebGL features in the client that are not yet widely supported.

Best,
Ladislav

**Comment by VrushalNCT** [comment]
Hello @ladislavhorky ,

Thanks for detailing the approaches.
I did an attempt to generate the glue with the plain spheroid but the glue failed after two days with the following log.

```2020-12-23 05:35:38 I3 [25495(add(dem)/1:dem_world_dem/21-331950-234665)]: (glue) progress:   8.50 %. {progress.cpp:report():48}
2020-12-23 07:35:12 I3 [25495(add(dem)/1:dem_world_dem/21-474773-149960)]: (glue) progress:   9.00 %. {progress.cpp:report():48}
2020-12-23 09:46:49 W2 [25495(add(dem)/1:dem_world_dem/18-56433-32320)]: Failed to fetch file from 
<http://<server_Ip>/mapproxy/melown2015/surface/melown/world_dem/18-56416-32320.meta?0>; retrying in 1000 ms. {httpfetcher.cpp:fetchAsStream():156}
2020-12-23 09:51:51 W2 [25495(add(dem)/1:dem_world_dem/20-225733-129280)]: Failed to fetch file from 
<http://<server_Ip>/mapproxy/melown2015/surface/melown/world_dem/20-225728-129280.meta?0>; retrying in 1000 ms. {httpfetcher.cpp:fetchAsStream():156}
```
It didn't find some tile. What could be the issue in this case?

I think adding an option in ```mapproxy-setup-resource``` will really help, which will auto-generate the plain tiles at all the area which is not covered by the data being processed. This will avoid the gluing step and can save considerable time.

**Comment by VrushalNCT** [comment]
> sorry, I think you might just have a huge glue dataset and have to wait it out.
> 
> It might be worth thinking about how to set up the original dataset so that `mapproxy-setup-resource` generates sea tiles everywhere. that would probably be the easiest solution.

@jrjdavidson @ladislavhorky Is there any such API option added in 'mapproxy-setup-resource' that generates sea tiles everywhere where the original dataset has no data? to save serious gluing time with the spheroid surface layer? Is there any future plan to add such an option to auto-generate the sea tiles?

**Comment by jrjdavidson** [comment]
Hi Vrushal, 

What I meant was to have an original dataset that covers the whole planet, i.e. fill in the gaps with 0. I'm sure it can be done with some GIS software, not sure how I would go about it though.

If you had a dataset with no gaps, that will reduce the need to generate glues. The less glues, the less processing it will take when running `mapproxy-setup-resource` .

By the way I'm not affiliate with melown, I'm just some random guy who thinks it's a great piece of software, so take whatever I say with a grain of salt!

Cheers,
JD
