### ISSUE TITLE
Is VTS Mapproxy optimized for Bing maps transactions?

### ISSUE THREAD

**Issue by VrushalNCT** [Melown/vts-backend#17]
I've setup mapproxy to use bing maps on a server.  
After loading bing maps several times in vts-browser, my server prompted that it's out of memory and everything stopped working after that.
Does VTS backend cache on the fly converted data? 
Is it optimized for Bing maps transactions? let's say, for instance. If we use the same geolocation to navigate each time in the vts browser, does mapproxy request those tiles from bing maps every time or returns some previously cached data?
Is this on the fly data conversion from not-vts to vts an expensive operation computationally? 
What is the recommended server configuration for this use case? (let's say for several hundred concurrent requests)

**Comment by vaclavblazek** [comment]
Hi, mapproxy does not cache data by itself. It sets HTTP caching headers based on configuration. It is also meant to be run behind caching HTTP proxy in serious installation. Please, have a look at `vts-backend` package that integrates mapproxy, vtsd and nginx.

**Comment by VrushalNCT** [comment]
Hello, 
I've followed this complete tutorial. [https://vts-geospatial.org/tutorials/vtsbackend.html](https://vts-geospatial.org/tutorials/vtsbackend.html)

And I think I've setup vtsd and nginx as well as per the tutorial.
After that I followed [https://vts-geospatial.org/tutorials/bing-maps.html](https://vts-geospatial.org/tutorials/bing-maps.html) to setup the bing-maps.
Is this a sufficient setup for vts backend (along with mapproxy) for using bing-maps?
Does this setup cache the converted data?
I'm worried why the server went out of memory after several usage. How much empty space required for cache data? how to configure it?

**Comment by ladislavhorky** [comment]
Hello @VrushalNCT,

based on your related [issue](https://github.com/melowntech/workshop/issues/33) in melowntech/workshop, I suggest you take a look on some more tutorials to get the idea about how various resource work together, general VTS concepts, and so on. I recommend my https://github.com/ladislavhorky/osm-based-3d-street-map as a good start which gives very high-level idea of the bound-layers (textures), surfaces (terrains) and vectors.

Otherwise, please describe clearly what are you trying to achieve, e.g. what you mean by "using bing-maps", your particular setup etc.
To your other questions:


"Does this setup cache the converted data?"
* In VTS-backend there is [some configurable caching done in nginx](https://github.com/melowntech/vts-backend/blob/e3cec0087cc35b1de61712d7ff0818cb65b0284b/vts-backend/etc/nginx/vts-backend#L2) - this file is present at `/etc/nginx/sites-available/vts-backend`. Though I am not sure now if this applies to Bing tiles - those may be downloaded directly from original URL. I believe the Bing Tiles should not be cached as it goes against their terms of use (I am not able to find particular clause though).

"Out of memory":
* This is hard to answer as you did not give any details whatsoever about your setup. Generally the disk space is consumed by cache - see above for configuration. Used memory can be configured in mapproxy [here](https://github.com/melowntech/vts-backend/blob/e3cec0087cc35b1de61712d7ff0818cb65b0284b/vts-backend/etc/mapproxy/mapproxy.conf#L119) - install location `/etc/vts/mapproxy/mapproxy.conf`. Bear in mind though, that lowering this too much may prevent vts-mapproxy from working properly.

Hope this helps,
Ladislav

**Comment by VrushalNCT** [comment]
Hello @ladislavhorky 

Thanks for your help.
I went through the concepts, tutorials and it helped me especially this one [https://github.com/ladislavhorky/osm-based-3d-street-map](https://github.com/ladislavhorky/osm-based-3d-street-map).
Let me give you a brief about what we're trying to achieve.

Our application needs high-resolution textures basically the details near the ground e.g. at a zoom level where we can see roads, buildings, etc clearly and 3d surface details also. We initially thought we'll host some data on the server itself but even 10m/px data sizes are huge (in several TBs and after processing it may again increase) so we later decided to use some services like bing-maps for high-resolution textures and let our servers use less memory.

Let me simplify my questions for you.

1. I'm using bing-maps as the bound layer with just spheroid-surface as a setup. Currently, I'm just doing a trial set up on a 15 GB storage server but it went out of memory. It can be due to other file storage also but, we will have at least 100GBs free for a production server, I hope it'll be sufficient.
2. If we want to consider setting up the DEM surface, do we have to download and setup DEM data on the server only? Are there any services available that provide the same, similar to bing-maps so that our server(vts-mapproxy) just converts all the data on the fly and doesn't need much storage? (What could be the size of the whole earth DEM data?).
3. We most probably want to use Maptiler as a tilemap service instead of bing maps, could you please help us with the resource definition for the same? I think the tms-bing driver is only for bing maps. Please, correct me if I'm wrong.

Thanks again for your help and for building such a great GIS tool.

**Comment by ladislavhorky** [comment]
Hello @VrushalNCT,

ad 1) 
15 G is really small, 100G really depends on DEM size an resolution - from context I see that DEM (plus cache) should be the thing that takes up space. If you have DEM in Geotiff with DEFLATE compression, it will roughly double after `mapproxy-setup-resourcce` processing. You may need to use --linkDataset (most up-to date package) to prevent copying original data.
The cache is configurable as I wrote. Based on usage, I'd set max 5000-10000m and key_zone to 1/10th of that (the latter being just a guess).

ad 2) 
I'd encourage you to setup your own. The external services would need to be served through VTS - WM(T)S DEM is not enough as mapproxy needs `min` and `max` overviews + standard overview to generate metadata. For the whole Earth 90m DEM, the original data have ~80G I believe -> ~160G after preprocessing. But the tiling may take some serious time depending on `--bottomLod`

ad 3)  
A TMS service will be fine as long as it matches the tiling scheme (webmerc TMS with melown2015 works fine). You'll want to use [tms-raster-remote](https://github.com/melowntech/vts-mapproxy/blob/master/docs/resources.md#driver-tms-raster-remote) driver, and use `loclod`, `locx` and `locy` in URL template. This way, only config of layer will be served from mapproxy, the rest will go directly from expanded URL template.

Hope it helps,
Ladislav

**Comment by VrushalNCT** [comment]
Thank you very much @ladislavhorky  It helped me a lot and tms-raster-remote driver worked. We can close this one.
