### ISSUE TITLE
Tutorial issue with Viking Global Mosaïc - blurred band

### ISSUE THREAD

**Issue by smoussally** [Melown/vts-backend#24]
I am following [this vts-backend tutorial ](https://vts-geospatial.org/tutorials/mars-peaks-and-valleys.html) (great job, btw) and some band of the global mosaïc appears blurred at low zoom levels : 
![Screenshot from 2021-06-21 23-02-09](https://user-images.githubusercontent.com/55635479/122827952-588e5a00-d2e5-11eb-998a-0ca317851c76.png)
This is a screenshot from the original tutorial but I can reproduce the issue with both the original .tif and the deflated .tif from melown's server with my own setup.

**Comment by vaclavblazek** [comment]
Unfortunately, it's caused by GDAL's raster I/O model. This place is spanning both eastern and western part of the source, i.e. around the +/-180 deg line that lies at the left and right edges of the raster.
However, GDAL can read only one continuous region, which is computed as a union of points of the source region. This causes the entire dataset to be read. Which cannot fit in memory at given resolution. So, lower resolution overview has to be used (which takes less RAM) => blur.
Known but not easily resolvable.

This also happens at Earth but but since there's mainly sea (and Antarctica) it's not so obvious.

One solution would be to split the surface into two, one half with the original dataset and the other with the dataset shifted by 180 degrees (i.e. spanning +180 to +360 deg). However, we have never tested it.

**Comment by smoussally** [comment]
Thanks for the answer. If I understand correctly, since GDAL can only read one continuous region to span both sides of the +/-180 longitude, it reads the full -180 to +180 region.
I am however not very sure I understand the possible solution, I would be glad if you could elaborate a bit:
If we need the dataset to cover the +/- 180 region continuously, shouldn't we shift the -180->0 region by 360 and paste it to the right of the dataset to obtain a -180->360 dataset (using gdalwarp to clip, translate and gdal_merge to paste), and maybe use the --wrapx parameter (not sure how, though).
Again, thanks for the help.

**Comment by vaclavblazek** [comment]
Well, I have not tested it, but the idea is to have a complement raster dataset that has left and right halves swapped -- this can be done via virtual dataset (VRT GDAL driver/module) or by `gdal_translate` to physically generate new TIFF that is georeferenced from 0 to 360.

The `--wrapx` parameter tells `generatevrtwo` (silly contraction of Generate VTR With Overviews) that the dataset is cyclic. So, it can replicate strip of data from left to right and vice versa. However, this is relevant only for generating overviews while downscaling; the filter kernel needs to see valid data behind the original image edge to properly downscale image at the edge. Without this setting you get visible artificial and ugly edge at the extremes.

The actual value of -`-wrapx` parameter (defaults to 0 when not stated) is an overlap in pixels that must be applied to make the data continuous. For orthophotos this value is 0 because orthophotos are made that the pixel edge lies at +/- 180/but for DEM/DTM/DSM this value is usually 1 because the actual sample (pixel center) at both extremes is at the same longitude. I know, it's too complex and GDAL is pushed to its boundaries in mapproxy.

**Comment by smoussally** [comment]
Ok, I see. If I summarize the steps that I will try, along the lines of tutorial:

1.  I create a new physical TIFF that runs from 0 to 360 by swapping the two halves of the original TIFF (I think I will try to do it with `gdal_translate` as I am not sure how to use the VRT GDAL driver).
2. I use `generatevrtwo` with `--resampling average` on each dataset to create two `.average1` and `.average2` files.
3. I create a new directory, let us say `mars-viking-mdim21`.
4. I create symbolic links to the two `.average/dataset` in `mars-viking-mdim21` directory.
5. The `.json` mapproxy resource conf file can stay as in tutorial (I guess).

Can something like this work?

**Comment by vaclavblazek** [comment]
It could work. Disclaimer: I have not tested dataset spanning 0-360, however it _should_ work.

Next thing is, you'd have to combine the two VTS surfaces into one which is kinda tricky. You could replace just the back side of the cube with the new surface, but you'd have to add both into a VTS storage. I.e. the original dataset would span tiles `[[0, 0], [2, 2]]` at LOD 2 and the new dataset would span only `[[3, 2], [3,2]]` at LOD 2.

However, the problem is also noticeable at polar caps since the +/-180 longitude line runs from north pole up and from south pole down in appropripate tiles. It is even more complicated to cover these. The easiest would be start at LOD 3, but you'd end up with 4 surfaces to combine: top of north cube face, bottom of north cube face, back face and the rest in the centre.

NB, the blurred area shrinks as you zoom in because the size of tiles spanning the edge of dataset shrinks.

The best solution would be to detect such degenerate states and split GDAL warp into multiple warps. But it's not simple.

For Earth, we use the "melown2015" reference frame where the most of the world is covered by tiles cut in webmercator space where this problem does not occur (no tile spands +/- 180 deg.). It is only visible in polar caps that use stereographic projections around both poles for space division.

**Comment by smoussally** [comment]
Would it make sense to convert the data from EPSG:4326 to EPSG:3857 and use the melown2015 reference frame?
Would it work?
