### ISSUE TITLE
Problem with our data

### ISSUE THREAD

**Issue by Azarchaniel** [Melown/vts-backend#4]
Hey, I tried your [tutorial](http://vtsdocs.melown.com/en/latest/tutorials/vtsbackend.html) and after many errors and tries, I had a working 3D map of Mars. Then I tried to use our own data and I failed.  I have a TIF. 4096x4096, no coor. syst.. Also I'm missing  `/var/run/vts-backend-mapproxy.ctrl`. Force update return me 
`socat [9352] E connect (5, AF=1 "/var/run/vts-backend-mapproxy.ctrl", 36): No such file or directory.`
Examples are running. 
Also, when I try `generetevrtwo`, I get `terminate called after throwing an instance of 'std::runtime_error'
  what():  Error parsing wkt definition: <5> (input = ). @{srs.cpp:import():64}
Aborted (core dumped)`
`/var/log/vts/mapproxy.log` is empty, but mapproxy.log.1 is [here](https://docs.google.com/document/d/10BDKxt5MjWbXHMhQREN9i-UM64u3bDjZ87SFprY1o7c/edit?usp=sharing)
Any help?

**Comment by vaclavblazek** [comment]
Hi Azarchaniel.

Re `generatewrto`: You stated that your TIF file has no coordinate system. That means it is not georeferenced and therefore it cannot be used in VTS. You have to georeference it (try [gdal_translate](http://www.gdal.org/gdal_translate.html)).

Re `force-update`: The `force-update` coomand in init script is used to signal **running** mapproxy instance that it should query resource backend (resource file in this case). Since your mapproxy is not running it cannot be signalled. You have to (re)start it.

I've peeked into your log file and it seems that you have some problem in config files. Top-level element in every resource json file must be list (i.e, []).

**Comment by vaclavblazek** [comment]
Mapproxy has been updated to support single resource file, i.e. `resource.json` can contain either array of resource definitions or single resource object.
